# auth

here my error after using this command alembic revision --autogenerate -m "Initial migration"

    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column object 'modified_at' already assigned to Table 'user_role'

 ![image](https://github.com/uhuddurmus/auth/assets/74601877/8997597b-6ee4-4c74-ac6d-97eecb4306f0)
